#ifndef __SERVER_DEFINE_H__
#define __SERVER_DEFINE_H__

enum EVENT_HANDLER {
    TYPE_LISTEN_FD = 10000,
    TYPE_NETWORK_FD = 10001,
    TYPE_PIPE_FD = 10002,
    TYPE_FILE_FD = 10003,
};

enum REACTOR_MSG_ID {
    MSG_ADD_FD = 11000,
};

enum MSG_HANDER_MSG_ID {
    MSG_DATA_BUFFER = 11500,
};

#endif